name: Benchmark

on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
      - run: yarn install
      - name: Get benchmark files
        id: benchmark-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            benchmarks:
              - benchmark/**
      - name: Run benchmark if test file(s) change
        id: benchmark-run
        if: steps.benchmark-files.outputs.test_any_changed == 'true'
        env:
          TEST_ALL_CHANGED_FILES: ${{ steps.benchmark-files.outputs.test_all_changed_files }}
        run: |
          yarn bench: $TEST_ALL_CHANGED_FILES --run
      - name: Comment on PR
        uses: wow-actions/auto-comment@v1
        if: steps.benchmark-files.outputs.test_any_changed == 'true'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            New benchmark found: $TEST_ALL_CHANGED_FILES, test result:
            ${{ join(steps.benchmark-run.outputs.*, '\n') }}
          pullRequestEdited: |
            New benchmark found: $TEST_ALL_CHANGED_FILES, test result:
            ${{ join(steps.benchmark-run.outputs.*, '\n') }}
